// Generated by 'unplugin-auto-import'
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
export {}
declare global {
  const IconFeBar: typeof import('~icons/fe/bar.jsx')['default'],
}
