// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IconGgArrowRight: typeof import('~icons/gg/arrow-right.jsx')['default']
  const IconGgCalendarToday: typeof import('~icons/gg/calendar-today.jsx')['default']
  const IconGgChart: typeof import('~icons/gg/chart.jsx')['default']
  const IconGgComment: typeof import('~icons/gg/comment.jsx')['default']
  const IconGgDollar: typeof import('~icons/gg/dollar.jsx')['default']
  const IconGgInfo: typeof import('~icons/gg/info.jsx')['default']
  const IconGgMathPlus: typeof import('~icons/gg/math-plus.jsx')['default']
  const IconGgMenu: typeof import('~icons/gg/menu.jsx')['default']
  const IconGgNotifications: typeof import('~icons/gg/notifications.jsx')['default']
  const IconGgSearch: typeof import('~icons/gg/search.jsx')['default']
  const IconGgSelect: typeof import('~icons/gg/select.jsx')['default']
  const IconGgUser: typeof import('~icons/gg/user.jsx')['default']
  const IconGgWebsite: typeof import('~icons/gg/website.jsx')['default']
}
